services:
  postgres:
    image: ankane/pgvector
    environment:
      POSTGRES_DB: eora_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d eora_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  eora-qa-service:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://user:password@postgres:5432/eora_db
      - ANTHROPIC_API_KEY=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
      - DEBUG=false
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    volumes:
      - ./logs:/app/logs

volumes:
  postgres_data:
