"""Remove answer_sources table - sources no longer stored in answers

Revision ID: a97ac508fa52
Revises: 9cf2b31b4289
Create Date: 2025-07-13 15:02:55.303206

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a97ac508fa52"
down_revision: str | Sequence[str] | None = "9cf2b31b4289"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("answer_sources")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "answer_sources",
        sa.Column("answer_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("source_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["answer_id"],
            ["answers.id"],
            name=op.f("answer_sources_answer_id_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["sources.id"],
            name=op.f("answer_sources_source_id_fkey"),
        ),
        sa.PrimaryKeyConstraint(
            "answer_id", "source_id", name=op.f("answer_sources_pkey")
        ),
    )
    # ### end Alembic commands ###
