# ============================================================================
# КОНФИГУРАЦИЯ TY - АЛЬТЕРНАТИВНАЯ СТАТИЧЕСКАЯ ПРОВЕРКА ТИПОВ
# ============================================================================

# === НАСТРОЙКИ ПРАВИЛ ===
[rules]
# Отключаем правило missing-argument для корректной работы с **kwargs
missing-argument = "ignore"

# === НАСТРОЙКИ ОКРУЖЕНИЯ ===
[environment]
# Целевая версия Python (соответствует project.requires-python в pyproject.toml)
python-version = "3.12"
